Added the Aruco Action Server
TrickfireRobotics/NasaRmc2018 pull request #14
Opened 2018-01-24 10:14 UTC by LinuxKid21

# Purpose
To integrate the openCV Aruco library as an action server in ROS

# What Got finished and what needs to be done still
The server is completely finished as is an example client. Right now there is no way to generate aruco boards and the position of the markers is done manually in the code. Aruco also has quite a few parameters, but I did not create a way to change those on the fly because it didn't seem necessary (in fact, the defaults seem to work the best anyway).
Some code is being repeated that only have to be done once, but I will fix that in a future poll request.

# Testing
You will need to print out the image file in the tfr_aruco folder (each marker will be 3.2 cm). I find it helpful to mark the top left corner when its done by putting an arrow to it.
You will need a webcam as well.
If you can't print or don't have a webcam then I will be happy to send you recorded messages(as soon as I figure out how to do that)
After building the program, run the following:
rosrun uvc_camera uvc_camera_node
rosrun tfr_aruco tfr_aruco_server
rosrun tfr_aruco tfr_aruco_example_client
I think these will run without camera calibration. If not then you may have to follow the uvc_camera calibration tutorial or just ask me for aforementioned recorded messages.

2018-01-24 23:56 UTC, collinsc commented
@LinuxKid21  I'll start my review. In the future if you need to spawn a series of nodes in sequence launch files or copy and pasteable actionx to do in a terminal window are the way to go if your reviewer needs to do manual testing.

However this time it should be fine.

2018-01-25 00:02 UTC, collinsc commented
@AdamuKaapan do you have any idea why jenkins isn't running on this node?

2018-01-25 00:35 UTC, collinsc commented
uvc_camera is deprecated, in a future commit let's move to libuvc it's successor

2018-01-25 00:59 UTC, collinsc commented
I found a bug: 
![image](https://user-images.githubusercontent.com/15841243/35365186-e6e0803c-0127-11e8-8d5e-20e1e0ad3d6e.png)

Detects image, but no location information.

2018-01-25 01:46 UTC, collinsc requested changes
So for sure there is a dependency issue, and this needs to be automated into a launch file for sure. Also we need to delete spurious callbacks/ check for preemption when appropriate. The way the action server is set up right now is not very maintainable, it needs to be refactored into a class at some point. I'll leave it up you if that is this pull request or the next one when you figure out what you want to do with the board.

2018-01-25 01:46 UTC, collinsc commented on src/tfr_msgs/CMakeLists.txt
>  find_package(catkin REQUIRED COMPONENTS
@LinuxKid21 @AdamuKaapan uvc_camera is an additional dependency that needs to be listed.

2018-01-25 01:46 UTC, collinsc commented on src/tfr_aruco/package.xml
> +  <exec_depend>tfr_msgs</exec_depend>
add uvc_camera

2018-01-25 01:46 UTC, collinsc commented on src/tfr_msgs/CMakeLists.txt
>  find_package(catkin REQUIRED COMPONENTS
It also needs to be added to the readme

2018-01-25 01:46 UTC, collinsc commented on src/tfr_aruco/src/tfr_aruco_example_client.cpp
> +}
If feedback isn't required it's better not to include it

2018-01-25 01:46 UTC, collinsc commented on src/tfr_aruco/src/tfr_aruco_example_client.cpp
> +        client.sendGoal(goal, &finished, NULL, &feedback);
yeah you can just pass in another  null param here for feedback

2018-01-25 01:46 UTC, collinsc commented on src/tfr_aruco/src/tfr_aruco_server.cpp
> +    cv::Ptr<cv::aruco::Dictionary> dictionary = cv::aruco::getPredefinedDictionary(cv::aruco::DICT_5X5_250);
You do not check for preemption at the beginning of an action, this needs to be fixed.

2018-01-25 02:03 UTC, LinuxKid21 commented on src/tfr_msgs/CMakeLists.txt
>  find_package(catkin REQUIRED COMPONENTS
@collinsc Well it sound like we should use libuvc instead. Also, I don't think it should be a dependency of my package. It takes in sensor_msgs/Image and sensor_msgs/CameraInfo which are produced by any camera package(or should be produced by any camera package).

2018-01-25 02:12 UTC, LinuxKid21 commented
@collinsc As for it saying 0, I'm not sure. I wonder if the Aruco function is refusing to work because you don't have the camera configured. (The warning in the message) Can you please try configuring your camera or use this [yaml](https://drive.google.com/open?id=1Uuua1hNISJEKH4EU6HZp8zrt0nE6DvAX) file? (if you use mine, then it should just return incorrect results, but something not 0. Also it will give a separate error saying that it looks like a different camera than the yaml).

2018-01-25 02:21 UTC, LinuxKid21 commented
@collinsc @AdamuKaapan Also, as far as Jenkins not running, I wonder if it's because I cloned the repository and tried merging that instead of creating a branch in this repository and merging that. I can close this commit and redo it that way if necessary.

2018-01-25 02:52 UTC, RyanBerge commented
@LinuxKid21 It probably would be best to make your changes in a branch off of this repository.  I'm not familiar enough with Git to know what the workflow looks like your way.

2018-01-25 06:24 UTC, collinsc commented on src/tfr_msgs/CMakeLists.txt
>  find_package(catkin REQUIRED COMPONENTS
Well when you write the launch file automating the code it will be.

2018-01-25 06:24 UTC, collinsc commented on src/tfr_msgs/CMakeLists.txt
>  find_package(catkin REQUIRED COMPONENTS
It will be a runtime dependency.

2018-01-25 06:27 UTC, collinsc commented
@LinuxKid21 The reason I think it is a bug, is that when it doesn't detect any markers and it's not near the sheet a string is displayed to the screen saying no markers found. When it get's close it displays that data, but all zeros. When I move it away it goes back to the no markers found bit.

I don't really care if it runs on my machine, but as long as it works on yours and the jetson robustly we are fine. I just can't look at your data.

Also how is it reporting data? Is this data saying the bin is this far away and this rotation from my reference frame? or is it saying I am this far away and at this rotation from the bin?

I think when we originally talked this was going to be a geometry_msgs/Pose? I think that would be a lot better. http://docs.ros.org/api/geometry_msgs/html/msg/Pose.html

2018-01-25 06:30 UTC, collinsc commented
@LinuxKid21 @RyanBerge  I also agree with ryan on this one, our tools and build server wont work with the fork approach.

2018-01-25 06:31 UTC, LinuxKid21 commented
Okay. I'll close this later and do it the right way. In the mean time, still leave comments here.

2018-01-25 06:37 UTC, collinsc commented
@LinuxKid21 
Cool Also another thing that came to me, what was the purpose in seperating this from the rest of the localization code in it's own package?

2018-01-25 07:09 UTC, LinuxKid21 commented
Hmmm... There's not a particular reason that they shouldn't be together. It just seemed better to separate them because the aruco code is able to it's own module. For example, putting it together would mean that all localization code would require the aruco module dependencies in its CMake. What does @Jebbs think?

2018-01-26 20:14 UTC, Jebbs requested changes
Looks good for the most part save for my suggestions. The one about `cameraImage` vs `cv_ptr->image` is more of my own opinion than a change I require, though.

There's also a lot of newlines in here which I think could be trimmed up a little, but maybe that is also just my opinion.

I didn't run any tests myself since @collinsc did and found errors, but using a recording to do the testing is mentioned in the pull request description. Could we add that as a test that could be automated?

2018-01-26 20:14 UTC, Jebbs commented on src/tfr_aruco/package.xml
> +  <maintainer email="levi@todo.todo">levi</maintainer>
You probably want to put in your full name here.

2018-01-26 20:14 UTC, Jebbs commented on src/tfr_aruco/package.xml
> +  <license>TODO</license>
Don't we have a license?

2018-01-26 20:14 UTC, Jebbs commented on src/tfr_aruco/package.xml
> +  <!-- <author email="jane.doe@example.com">Jane Doe</author> -->
Everyone who worked on this should be listed here.

2018-01-26 20:14 UTC, Jebbs commented on src/tfr_aruco/src/tfr_aruco_server.cpp
> +    cv::Ptr<cv::aruco::Board> board = cv::aruco::Board::create(std::move(boardCorners), dictionary, std::move(boardIds));
If the aruco board is always the same (or is always going to be the same), then it should be predefined and made constant.

2018-01-26 20:14 UTC, Jebbs commented on src/tfr_aruco/src/tfr_aruco_server.cpp
> +    int v = cv::aruco::estimatePoseBoard(markerCorners, markerIds, board, cameraMatrix, distCoeffs, boardRotVec, boardTransVec);
`v` is not very descriptive as a variable name.

2018-01-26 20:14 UTC, Jebbs commented on src/tfr_aruco/src/tfr_aruco_server.cpp
> +    if(v != 0)
Will `v` ever be less than zero? If not, then `if (v>0)` might read better. This would be even more true with a different variable name.

I would also move the `// if v = 0, then no marker was detected` comment to be referencing this if statement.

2018-01-26 20:14 UTC, Jebbs commented on src/tfr_aruco/src/tfr_aruco_server.cpp
> +    cv::aruco::detectMarkers(cameraImage, dictionary, markerCorners, markerIds, params);
You say that using `cameraImage` is the same as using `cv_ptr->image`, but you only use it once. You could get the same clarity by renaming `cv_ptr` to something more meaningful, like `cameraData`. Then you could use `cameraData->image` and it is just as clear.

2018-01-27 08:13 UTC, collinsc commented on src/tfr_aruco/package.xml
> +  <license>TODO</license>
BSD baby! Let's put that in there

2018-02-01 02:48 UTC, collinsc commented
Hey I got a version of this branch working on the jetson w/ a launch file. I needed a way to test the rear camera I set up and it works pretty decent. So I don't know what was going on with my laptop, but it works with the jetson, which is what matters at the end of the day.

2018-02-02 19:18 UTC, closed without merging