Nav mining point
TrickfireRobotics/NasaRmc2018 pull request #25
Opened 2018-02-02 19:00 UTC by collinsc

# Description
As with the proposed requirements change to move away from the the mining line and get to the mining point. See the pull request on documentation to do so. This pull request implements that change.

# Prerequisite
This code is an additive change to #21, and we need to discuss it as a team so we can't finish it until we do both of those things.

# Testing 
This was tested and verified in the same way as #21, so unfortunately you cannot do any testing at home beyond building and re running the unit tests.

2018-02-03 22:44 UTC, RyanBerge requested changes
I'm gonna wait on a review for this PR until a couple other ones get merged, because there are 36 files changed but most of them are changes I already reviewed and I don't want to parse out the new ones.  Once the other two PRs are done and this is rebased the diff will be a lot easier to read.

2018-02-03 23:53 UTC, collinsc commented
Yeah It's only the last commit that is relevant, but I agree, if I have to change the other branch I would need to rebase the changes I made here anyway.

2018-02-09 04:07 UTC, AdamuKaapan commented on src/tfr_navigation/src/navigator.cpp
> + * Prepare a feedback message for sending
Wrong comment? Should be "prepare a result message for sending"?

2018-02-09 04:08 UTC, AdamuKaapan submitted a review, later dismissed
Left a small comment about a comment, can be fixed at a later PR.

2018-02-09 18:16 UTC, collinsc commented
@AdamuKaapan I fixed that comment, for some reason your comment did not get carried over when I rebased.

2018-02-09 19:08 UTC, RyanBerge approved these changes

2018-02-09 19:50 UTC, merged